FROM wordpress:latest

RUN apt-get update
RUN apt-get install -y less
RUN apt-get install -y wget
RUN apt-get install -y gettext

WORKDIR /tmp

# WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN ls -l
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

# COMPOSER
RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
RUN echo EXPECTED_SIGNATURE
RUN echo $EXPECTED_SIGNATURE
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
RUN if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then echo "Installer corrupt"; rm composer-setup.php; else echo "Installer verified"; fi
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

#PHPUNIT
RUN wget https://phar.phpunit.de/phpunit-8.2.phar
RUN mv phpunit-8.2.phar /usr/local/bin/phpunit
RUN chmod +x /usr/local/bin/phpunit

WORKDIR /var/www/html
